development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: CONSULT_DEV
  pool: 5
  username: dev
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: CONSULT_TEST
  pool: 5
  username: dev
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: CONSULT_PROD
  pool: 5
  username: root
  password:
